name = "cf-r2-webdav"
main = "src/index.ts"
compatibility_date = "2023-01-01"

[vars]
USERNAME = "740839751"
PASSWORD = "zpwp7539087"
BUCKET_NAME = "bucket"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "webdav"